/**
 * CLASE QUE IMPLEMENTARÁ TODOS LOS MÉTODOS QUE ESTAN RELACIONADOS CON LA MULTIPLICACIÓN DE LA CALCULADORA.
 * @author SERGIO MARTÍNEZ RIVERA
 * @version 1
 *
 */
public class Producto {

	/**
	 * METODO QUE CALCULA LA MULTIPLICACIÓN DE DOS NÚMEROS REALES. 
	 * 
	 * @param numero1 REPRESENTA EL PRIMER NUMERO REAL DE LA MULTIPLICACIÓN.
	 * @param numero2  REPRESENTA EL SEGUNDO NUMERO REAL DE LA MULTIPLICACIÓN.
	 * 		  
	 * @return RETORNARA UNA CADENA QUE CONTIENE EL RESULTADO DE LA MULTIPLICACIÓN 
	 *  REDONDEADA A DOS DECIMALES HACIENDO USO DEL Math.round.
	 */
	public String ProductoReales (double numero1, double numero2) { 

		return "";
		
	}
	
	/**
	 * METODO QUE CALCULA LA MULTIPLICACIÓN DE DOS NÚMEROS ENTEROS. 
	 * 
	 * @param numero1  REPRESENTA EL PRIMER NUMERO ENTERO DE LA MULTIPLICACIÓN.
	 * @param numero2  REPRESENTA EL SEGUNDO NUMERO ENTERO DE LA MULTIPLICACIÓN.
	 * 		  
	 * @return RETORNARA UNA CADENA QUE CONTIENE EL RESULTADO DE LA MULTIPLICACIÓN..
	 * @deprecated EL MÉTODO {@link #ProductoReales (double, double)} TAMBIÉN ME CALCULA DOS NÚMEROS ENTEROS.
	 */
	
	
	public String ProductoEnteros (int numero1, int numero2) {

		return "";
		
	}
	
	/**
	 * METODO QUE CALCULA LA MULTIPLICACIÓN DE DOS NÚMEROS REALES. 
	 * 
	 * @param numero1  REPRESENTA EL PRIMER NÚMERO REAL DE LA MULTIPLICACIÓN.
	 * @param numero2  REPRESENTA EL SEGUNDO NÚMERO REAL DE LA MULTIPLICACIÓN.
	 * @param numero3  REPRESENTA EL TERCER NÚMERO REAL DE LA MULTIPLICACIÓN	  
	 * @return RETORNARA UNA CADENA QUE CONTIENE EL RESULTADO DE LA MULTIPLICACIÓN 
	 *  REDONDEADA A DOS DECIMALES, HACIENDO USO DEL Math.round.
	 */
	
	public  String ProductoTresReales ( double numero1, double numero2, double numero3) {

		return "";
		
	}
	
	/**
	 * METODO QUE CALCULA EL RESULTADO DE UNA POTENCIA.
	 * LA POTENCIACIÓN ES UNA OPERACIÓN QUE CONSISTE EN MULTIPLICAR POR SÍ MISMO UN NÚMERO PRINCIPAL LLAMADO BASE,
	 * TANTAS VECES COMO LO INDIQUE OTRO NÚMERO QUE SE LLAMA EXPONENTE.
	 * @param base NÚMERO REAL O ENTERO QUE SERVIRÁ COMO BASE DE LA POTENCIA.
	 * @param exponente NÚMERO REAL O ENTERO QUE SERVIRÁ COMO EXPONENTE DE LA POTENCIA.
	 * @return  RETORNARA UNA CADENA QUE CONTIENE EL RESULTADO DE LA POTENCIA REDONDEADA
	 *  A DOS DECIMALES, HACIENDO USO DEL Math.round. DARÁ ERROR SI EL RESULTADO ES MAS GRANDE DE UN DOUBLE.
	 */
	
	public String Potencia (double base, double exponente) {

		return "";
		
	}
}
